package com.sample.common.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sample.common.database.EffectInfo;

import com.sample.common.database.EffectInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig effectInfoDaoConfig;

    private final EffectInfoDao effectInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        effectInfoDaoConfig = daoConfigMap.get(EffectInfoDao.class).clone();
        effectInfoDaoConfig.initIdentityScope(type);

        effectInfoDao = new EffectInfoDao(effectInfoDaoConfig, this);

        registerDao(EffectInfo.class, effectInfoDao);
    }
    
    public void clear() {
        effectInfoDaoConfig.clearIdentityScope();
    }

    public EffectInfoDao getEffectInfoDao() {
        return effectInfoDao;
    }

}
